import { z } from "zod";
import { AssignmentCommandError, safeAssignmentError } from "./workOrderAssignmentCommands";

// Only the existing manual form vocabulary crosses this adapter. Assignment
// eligibility, provenance and atomic persistence remain database-owned.
export const manualWorkOrderSchema = z.object({
  id: z.string().min(1), incidentId: z.string().nullable().optional(),
  store: z.string().optional(), city: z.string().optional(), addr: z.string().optional(),
  storeState: z.string().nullable().optional(), storeTimezone: z.string().nullable().optional(),
  lineOfService: z.string().optional(), businessService: z.string().optional(),
  category: z.string().optional(), subCategory: z.string().optional(),
  summary: z.string().optional(), description: z.string().optional(),
  priority: z.enum(["p1", "p2", "p3", "p4", "p5"]),
  status: z.enum(["assigned", "unassigned"]), functionalStatus: z.enum(["New", "Dispatched"]),
  contractor: z.uuid().nullable(), afm: z.string().optional(), afmEmail: z.string().optional(),
  nte: z.number().finite().nonnegative().optional(), isCapital: z.boolean().optional(),
  dispatchedAt: z.iso.datetime({ offset: true }).nullable(),
  slaStartedAt: z.iso.datetime({ offset: true }).nullable().optional(), source: z.literal("manual"),
});
export type ManualWorkOrderInput = z.infer<typeof manualWorkOrderSchema>;
function fingerprint(input: ManualWorkOrderInput) {
  // These are generated by the form on each click, not a changed user command.
  const { dispatchedAt, ...rest } = input;
  void dispatchedAt;
  return JSON.stringify(rest);
}
export function createWorkOrderCreationAttempt(input: unknown) {
  const workOrder = manualWorkOrderSchema.parse(input);
  const identity = fingerprint(workOrder);
  const operationId = crypto.randomUUID();
  const startedAt = workOrder.slaStartedAt || new Date().toISOString();
  let active = false;
  return {
    matches(next: unknown) { return fingerprint(manualWorkOrderSchema.parse(next)) === identity; },
    async run<Result>(execute: (workOrder: ManualWorkOrderInput, operationId: string, startedAt: string) => Promise<Result>) {
      if (active) throw new AssignmentCommandError("ASSIGNMENT_BUSY", "Work-order creation is already in progress.");
      active = true;
      try { return await execute(workOrder, operationId, startedAt); }
      catch (error) { throw safeAssignmentError(error); }
      finally { active = false; }
    },
  };
}
