// Frozen vulnerability characterization, NOT a supported persistence adapter.
// Captured from src/lib/db.ts on fix/stabilize-app, 2026-09-09, before Batch 2C.
// Contains only the two unchanged legacy photo functions; no customer data.
// Production acceptance must be tested separately, never against this fixture.
export const LEGACY_PHOTO_SOURCE_SHA256 = "d1331d5d76618de4cd0fd384c39169bb05b7d95f92a1a39f9fc951fb942ec55f";
export const LEGACY_PHOTO_SOURCE = [
  "export async function uploadPhotos(",
  "  workOrderId: string,",
  "  files: FileList | File[],",
  "  authorName: string,",
  "  audit: ActivityAuditOptions = {},",
  "): Promise<string[]> {",
  "  const sb = supabase();",
  "  const { data: { user } } = await sb.auth.getUser();",
  "  const uploaded: string[] = [];",
  "  const arr = Array.from(files);",
  "  for (const file of arr) {",
  "    const ext = (file.name.split(\".\").pop() || \"jpg\").toLowerCase();",
  "    const filename = `${Date.now()}_${crypto.randomUUID()}`;",
  "    const path = `wo/${workOrderId}/${filename}.${ext}`;",
  "    const { error: upErr } = await sb.storage.from(\"photos\").upload(path, file, { contentType: file.type, upsert: false });",
  "    if (upErr) throw upErr;",
  "    const { error: rowErr } = await sb.from(\"photos\").insert({",
  "      work_order_id: workOrderId,",
  "      storage_path: path,",
  "      uploader_id: user?.id || null,",
  "      uploader_name: authorName,",
  "    });",
  "    if (rowErr) throw rowErr;",
  "    uploaded.push(path);",
  "  }",
  "  if (uploaded.length > 0) {",
  "    await insertActivity(workOrderId, authorName, `Added ${uploaded.length} photo${uploaded.length > 1 ? \"s\" : \"\"}.`, \"note\", audit);",
  "  }",
  "  return uploaded;",
  "}",
  "",
  "export async function removePhoto(workOrderId: string, storagePath: string): Promise<{ success: boolean; error?: unknown }> {",
  "  const sb = supabase();",
  "  // Delete the row (RLS allows uploader or staff)",
  "  const { data: deletedRows, error: dbError } = await sb",
  "    .from(\"photos\")",
  "    .delete()",
  "    .eq(\"work_order_id\", workOrderId)",
  "    .eq(\"storage_path\", storagePath)",
  "    .select(\"id\");",
  "  if (dbError) return { success: false, error: dbError };",
  "  if (!deletedRows || deletedRows.length === 0) {",
  "    return { success: false, error: new Error(\"Only the uploader or a staff member can delete this image\") };",
  "  }",
  "  // Delete the file from storage",
  "  const { error: storageError } = await sb.storage.from(\"photos\").remove([storagePath]);",
  "  if (storageError) return { success: false, error: storageError };",
  "  return { success: true };",
  "}",
].join("\n");
