/** Names-only inventory for explicit local preflight. Never imported by UI. */
export const CONFIGURATION_ENVIRONMENT_NAMES = [
  "NEXT_PUBLIC_SUPABASE_URL", "NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY", "SUPABASE_SECRET_KEY", "P1_EXPECTED_SUPABASE_PROJECT_REF",
  "P1_PRODUCTION_SUPABASE_PROJECT_REF", "P1_GRAPH_ENV", "P1_TWILIO_ENV", "P1_ALLOW_PREVIEW_PROVIDER_ACTIONS",
  "NEXT_PUBLIC_APP_URL", "PORTAL_URL", "NODE_ENV", "VERCEL_ENV", "P1_APP_ENV", "NEXT_PUBLIC_P1_APP_ENV", "VERCEL_PROJECT_PRODUCTION_URL", "VERCEL_GIT_COMMIT_SHA", "P1_ALLOW_PREVIEW_JOBS",
  "CRON_SECRET", "OUTLOOK_TENANT_ID", "OUTLOOK_CLIENT_ID", "OUTLOOK_CLIENT_SECRET", "OUTLOOK_USER_EMAIL", "OUTLOOK_FOLDER_NAME", "NOTIFY_OWNER_EMAILS",
  "EMAIL_INTAKE_ENABLED", "EMAIL_INTAKE_START_AT", "EMAIL_INTAKE_RECOVERY_LOOKBACK_HOURS", "EMAIL_INTAKE_ALLOWED_SENDERS", "EMAIL_INTAKE_ALLOWED_STATES",
  "EMAIL_INTAKE_TEXAS_ENABLED", "EMAIL_INTAKE_FLORIDA_START_AT", "EMAIL_PRIORITY_INTAKE_START_AT",
  "TWILIO_ACCOUNT_SID", "TWILIO_API_KEY_SID", "TWILIO_API_KEY_SECRET", "TWILIO_AUTH_TOKEN", "TWILIO_MESSAGING_SERVICE_SID", "TWILIO_FROM_NUMBER",
  "QUICKBOOKS_ENVIRONMENT", "QUICKBOOKS_SANDBOX_CLIENT_ID", "QUICKBOOKS_SANDBOX_CLIENT_SECRET", "QUICKBOOKS_SANDBOX_REDIRECT_URI",
  "QUICKBOOKS_PRODUCTION_CLIENT_ID", "QUICKBOOKS_PRODUCTION_CLIENT_SECRET", "QUICKBOOKS_PRODUCTION_REDIRECT_URI", "QUICKBOOKS_TOKEN_ENCRYPTION_KEY",
  "QUICKBOOKS_TOKEN_KEY_VERSION", "QUICKBOOKS_TOKEN_ENCRYPTION_KEY_V<N>",
] as const;
